#!/usr/bin/env python3
"""Generate src/maze.js from the floorplan extracted out of the original Panda3D model.

Usage:  python3 tools/gen_maze.py [tools/maze.json]

maze.json comes from tools/extract_maze.py described in README.md: the original
models/solidfloormazefinal.egg is loaded in Panda3D and ray-cast scanline-by-scanline
at player height to find every wall surface, then flood-filled from the player spawn
to isolate the reachable playfield.
"""
import json
import os
import sys
from collections import deque

# Must match T.playerR in src/game.js, plus a little margin. Every pickup has to sit
# somewhere the player's collision circle can actually reach.
PLAYER_CLEARANCE = 3.4

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, os.pardir, "src", "maze.js")
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "maze.json")

d = json.load(open(SRC))
CELL, W, H = d["cell"], d["w"], d["h"]
x0, y0 = d["originX"], d["originY"]
rows = [[int(c) for c in r] for r in d["grid"]]   # row 0 == min Y
rows = rows[::-1]                                  # flip so row 0 == max Y (screen top)
topY = y0 + H * CELL


def to_cell(wx, wy):
    return int((wx - x0) / CELL), int((topY - wy) / CELL)


def cell_center(i, j):
    return x0 + (i + 0.5) * CELL, topY - (j + 0.5) * CELL


def clear_at(wx, wy, r):
    """Circle-vs-grid, mirroring hitsWall() in game.js."""
    i0, i1 = int((wx - r - x0) / CELL), int((wx + r - x0) / CELL)
    j0, j1 = int((topY - (wy + r)) / CELL), int((topY - (wy - r)) / CELL)
    for j in range(j0, j1 + 1):
        for i in range(i0, i1 + 1):
            if not (0 <= i < W and 0 <= j < H):
                return False
            if rows[j][i] == 0:
                continue
            rx0, rx1 = x0 + i * CELL, x0 + (i + 1) * CELL
            ry1, ry0 = topY - j * CELL, topY - (j + 1) * CELL
            cx = min(max(wx, rx0), rx1)
            cy = min(max(wy, ry0), ry1)
            if (wx - cx) ** 2 + (wy - cy) ** 2 < r * r:
                return False
    return True


def snap(wx, wy):
    """Nudge a spawn to the nearest spot the player can actually stand in."""
    if clear_at(wx, wy, PLAYER_CLEARANCE):
        return wx, wy, False
    si, sj = to_cell(wx, wy)
    seen = {(si, sj)}
    dq = deque([(si, sj)])
    while dq:
        i, j = dq.popleft()
        cx, cy = cell_center(i, j)
        if clear_at(cx, cy, PLAYER_CLEARANCE):
            return round(cx, 1), round(cy, 1), True
        for di, dj in ((1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (1, -1), (-1, 1), (-1, -1)):
            n = (i + di, j + dj)
            if n not in seen and 0 <= n[0] < W and 0 <= n[1] < H:
                seen.add(n)
                dq.append(n)
    return wx, wy, False


# --- run-length encode, hex lengths, runs alternate open/wall starting with open ---
flat = [c for r in rows for c in r]
runs, cur, n = [], 0, 0
for v in flat:
    if v == cur:
        n += 1
    else:
        runs.append(n)
        cur = v
        n = 1
runs.append(n)
enc = ".".join(format(r, "x") for r in runs)

# --- entity tables, straight out of FINALtheamazeingrace.py ---
ENEMIES = [("cheken", -249, 419, "X"), ("chris", -404, 343, "X"), ("fetus", -141, -69, "X"),
           ("cheken", -277, 356, "Y"), ("rose", -102, -5, "Y"), ("cheken", -133, 83, "Y"),
           ("fetus", -246, 280, "X"), ("cheken", -330, 241, "X"), ("chris", -60, 110, "Y"),
           ("fetus", -75, 52, "X"), ("cheken", -75, 141, "X"), ("rose", -302, 202, "X"),
           ("chris", -303, 304, "Y")]
ORBS = [(18, 29, "red"), (-249, 419, "white"), (-404, 343, "yellow"), (-141, -69, "blue"),
        (-277, 356, "yellow"), (-102, -5, "blue"), (-135, 22, "blue"), (-248, 329, "white"),
        (-330, 241, "yellow"), (-60, 110, "red")]
DONUTS = [(0, 0), (-330, 250), (-141, -80), (-249, 430), (-102, -10)]

moved = []


def place(tag, x, y):
    nx, ny, did = snap(x, y)
    if did:
        moved.append("%s (%g, %g) -> (%g, %g)" % (tag, x, y, nx, ny))
    return nx, ny


enemies = []
for t, x, y, a in ENEMIES:
    nx, ny = place("enemy " + t, x, y)
    enemies.append({"t": t, "x": nx, "y": ny, "axis": a})

orbs = []
for x, y, c in ORBS:
    nx, ny = place("orb", x, y)
    orbs.append({"x": nx, "y": ny, "c": c})

donuts = []
for x, y in DONUTS:
    nx, ny = place("donut", x, y)
    donuts.append({"x": nx, "y": ny})

px, py = place("player", 25, -1)
gx, gy = place("portal", -196, 177)

js = f"""// Generated by gen_maze.py - do not edit by hand.
// The floorplan is the REAL one: extracted from models/solidfloormazefinal.egg in the
// original Panda3D project by scanline ray-casting the mesh at player height, then
// flood-filled from the player spawn to isolate the reachable playfield.
(function (global) {{
  "use strict";

  const RLE = "{enc}";
  const GW = {W}, GH = {H};

  // Runs alternate open/wall, starting with open; lengths are hex.
  function decodeGrid() {{
    const g = new Uint8Array(GW * GH);
    let p = 0, wall = 0;
    for (const part of RLE.split(".")) {{
      const n = parseInt(part, 16);
      if (wall) g.fill(1, p, p + n);
      p += n; wall ^= 1;
    }}
    return g;
  }}

  global.MAZE = {{
    CELL: {CELL}, GW, GH,
    ORIGIN_X: {x0}, TOP_Y: {topY},
    decodeGrid,
    SPAWN:  {{ x: {px}, y: {py} }},
    PORTAL: {{ x: {gx}, y: {gy} }},
    ENEMIES: {json.dumps(enemies)},
    ORBS:    {json.dumps(orbs)},
    DONUTS:  {json.dumps(donuts)}
  }};
}})(window);
"""
open(OUT, "w").write(js)

print("wrote src/maze.js  (%d runs, %.1f KB encoded)" % (len(runs), len(enc) / 1024))
print("grid %dx%d — %d wall cells, %d open" % (W, H, sum(flat), len(flat) - sum(flat)))
if moved:
    print("snapped %d spawn(s) to reachable floor:" % len(moved))
    for m in moved:
        print("   ", m)
else:
    print("no spawns needed snapping")

everything = ([(px, py), (gx, gy)]
              + [(e["x"], e["y"]) for e in enemies]
              + [(o["x"], o["y"]) for o in orbs]
              + [(d["x"], d["y"]) for d in donuts])
bad = [p for p in everything if not clear_at(p[0], p[1], PLAYER_CLEARANCE)]
print("reachability check: %d/%d spawns have player clearance%s"
      % (len(everything) - len(bad), len(everything), "" if not bad else "  BAD: %s" % bad))
